swagger: "2.0"
info:
  version: "0.0.1"
  title: Hello World App
# during dev, should point to your local machine
host: localhost:10010
# basePath prefixes all resource paths 
basePath: /
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /job-listings:
    x-swagger-router-controller: job_listing
    #Route: Get all job listings.
    get:
        operationId: getAll
        description: get all job listings
        responses:
          "200":
            description: Success
            schema:
              $ref: "#/definitions/GetJobListingsResponse"
          default:
            description: Error
            schema:
              $ref: "#/definitions/ErrorResponse"
    #Route: Post/create a new job listing.
    post:
        operationId: save
        description: create a new job listing
        parameters:
          - name: title
            description: Job listing details
            in: body
            required: true
            schema:
              $ref: "#/definitions/JobListing"
        responses:
          "200":
            description: Success
            schema:
              $ref: "#/definitions/JobListingCreatedResponse"
          default:
            description: Error
            schema:
              $ref: "#/definitions/ErrorResponse"
  /job-listings/{id}:
      x-swagger-router-controller: job_listing
      #Route: Get all job listings.
      get:
          operationId: getById
          description: get a single job listing by id
          parameters:
           - name: id
             type: string
             in: path
             required: true
          responses:
            "200":
              description: Success
              schema:
                $ref: "#/definitions/GetJobListingByIdResponse"
            default:
              description: Error
              schema:
                $ref: "#/definitions/ErrorResponse"
      put:
          operationId: update
          description: update a job listing by id
          parameters:
           - name: id
             description: the job listing id
             type: string
             in: path
             required: true
           - name: title
             description: the title of the job listing
             in: body
             required: false
             schema:
               $ref: "#/definitions/JobListingUpdate"
          responses:
            "200":
              description: Success
              schema:
                $ref: "#/definitions/JobListingUpdatedResponse"
            default:
              description: Error
              schema:
                $ref: "#/definitions/ErrorResponse"
      delete:
          operationId: remove
          description: remove a job listing by id
          parameters:
            - name: id
              description: the id of the job listing
              type: string
              in: path
              required: true
          responses:
            "200":
              description: Success
              schema:
                $ref: "#/definitions/JobListingRemovedResponse"
            default:
              description: Error
              schema:
                $ref: "#/definitions/ErrorResponse"
  /swagger:
    x-swagger-pipe: swagger_raw
# complex objects have schema definitions
definitions:
  GetJobListingByIdResponse:
      required:
        - id
        - title
        - job_description
        - is_active
        - applicants
      properties:
        id:
          type: string
        title:
          type: string
        job_description:
          type: string
        is_active:
          type: boolean
        applicants:
          type: array
          items:
            type: object
            required:
              - id
              - name
              - surname
              - email
              - cell_no
              - status
            properties:
              id:
                type: string
              name:
                type: string
              surname:
                type: string
              email:
                type: string
              cell_no:
                type: string
              status:
                type: boolean
  GetJobListingsResponse:
    required:
      - job_listings
    properties:
      job_listings:
        type: array
        items:
          type: object
          properties:
            id:
              type: string
            title:
              type: string
            description:
              type: string
            is_active:
              type: boolean
  JobListing:
    type: object
    required:
      - title
      - job_description
      - is_active
    properties:
      title:
        type: string
        description: job listing name
      job_description:
        type: string
        description: a description of the job
      is_active:
        type: boolean
        description: is the job listing active
  JobListingUpdate:
    type: object
    properties:
      title:
        type: string
        description: job listing name
      job_description:
        type: string
        description: a description of the job
      is_active:
        type: boolean
        description: is the job listing active
  JobListingCreatedResponse:
    type: object
    required:
      - success
      - description
    properties:
      success:
        type: integer
        description: returns 1 if successful
      description:
        type: string
        description: the job listing was updated successfully
  JobListingUpdatedResponse:
    type: object
    required:
      - success
      - description
    properties:
      success:
        type: integer
        description: returns 1 if successful
      description:
        type: string
        description: the job listing was created successfully
  JobListingRemovedResponse:
    type: object
    required:
      - success
      - description
    properties:
      success:
        type: integer
        description: returns 1 if successful
      description:
        type: string
        description: the job listing was removed successfully
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
